name: Make TWRP Device

on:

  workflow_dispatch:

    inputs:

      IMG_URL:    

        description: 'IMG_URL'

        required: true

        default: ''

jobs:

  build:

    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-20.04

    permissions:

     contents: write

    steps:

    - name: Check Out

      uses: actions/checkout@main

      

    - name: Prepare the environment

      run: |

        sudo apt update

        sudo apt -y install python3 python3-pip cpio wget

        pip3 install aospdtgen

        mkdir dt

      

    - name: Download boot or recovery img
      run: |
       wget https://github.com/Samsung-Loki/Syndical/releases/download/v1.0.1/Syndical.Application-linux.zip
       unzip *.zip
       rm *.zip
       cd Debug/net5.0
       ./Syndical.Application -m DownloadDecrypt -v A233CONU1BWE2/A233CQKT1BWE2/A233CONU1BWE2 -M SM-A233C -r RKT -f
      
    - name: Start build
      run: |

        

    - name: ZIP device tree

      run: |

    
    - name: Upload to Release

      uses: softprops/action-gh-release@v1

      with:

        files: |

          ./*.zip

        name: TWRP_Device_Tree-${{ github.run_id }}

        tag_name: ${{ github.run_id }}

        body: DeviceTree for twrp

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
