name: Make TWRP Device

on:

  workflow_dispatch:

    inputs:

      IMG_URL:    

        description: 'IMG_URL'

        required: true

        default: ''

jobs:

  build:

    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-20.04

    permissions:

     contents: write

    steps:

    - name: Check Out

      uses: actions/checkout@main

      

    - name: Prepare the environment

      run: |

        sudo apt update

        sudo apt -y install python3 python3-pip cpio wget

        pip3 install aospdtgen dumpyara

        mkdir dt

      

    - name: Download boot or recovery img
       FILE_ID=1_hUJpqV30zFszkBNFmFUG_swy1TLKD9P
       curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${FILE_ID}" > /dev/null
       CODE="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
       curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${CODE}&id=${FILE_ID}" -o sam.zip
    - name: Start build
      run: |

        

    - name: ZIP device tree

      run: |

    
    - name: Upload to Release

      uses: softprops/action-gh-release@v1

      with:

        files: |

          ./*.zip

        name: TWRP_Device_Tree-${{ github.run_id }}

        tag_name: ${{ github.run_id }}

        body: DeviceTree for twrp

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
